name:                phylocursive
version:             0.1.0
github:              "githubuser/phylocursive"
license:             BSD3
author:              "Zebulun Arendsee"
maintainer:          "zbwrnz@gmail.com"
copyright:           "2021 Zebulun Arendsee"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            A phylogenetics library based on recursion schemes
# category:            Science

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/phylocursive#readme>

dependencies:
  - base >= 4.7 && < 5
  - random
  - safe
  - timeit
  - prettyprinter >=1.2.0.1 && <1.8

library:
  source-dirs: src

executables:
  phylocursive-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - phylocursive

tests:
  phylocursive-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - phylocursive
